Process RPC Socket error instead of panicing
Testing with bpfd as a systemd service, hit a case where bpfd had a permission
error on the socket. Adding logic to process the error instead of panicing.

Error:
Aug 18 08:31:18 ebpf03 bpfd[214717]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EACCES', bpfd/src/server/bpf.rs:270:87
Aug 18 08:31:18 ebpf03 bpfd[214717]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aug 18 08:31:18 ebpf03 bpfd[214717]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', bpfd/src/server/rpc.rs:197:33
Aug 18 08:31:18 ebpf03 systemd[1]: bpfd.service: Main process exited, code=exited, status=101/n/a
Aug 18 08:31:18 ebpf03 systemd[1]: bpfd.service: Failed with result 'exit-code'.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>