bpfman: Cleanup after failed load attempt
If a program partially loads then fails, bpfman can be left in a bad
state where bpfman panics on future list requests.

```
sudo bpfman list --all
thread 'main' panicked at bpfman/src/bpf.rs:214:52:
Failed to build program from database: Error("Program id does not match database id program isn't fully loaded")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So delete partial program on any failed requests.

Also, the `program.delete()` function was regenerating the database tree
name. On a load, a temporary tree with a different prefix is used
until the kernel id is obtained. Because of this, it was computing the
wrong database tree name and failing to delete partially created
program.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>