Only members of bpfd user group should be able to access certs
Only privileged users or users that are a member of the bpfd User Group should
be able to access certs files or the unix socket file. Certs was currently allowing
any user access to the certs files:

BEFORE:
```
$ id
uid=1000(bmcfall) gid=1000(bmcfall) groups=1000(bmcfall),10(wheel),981(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

$ RUST_LOG=info bpfctl list
[2023-04-21T19:25:01Z WARN  bpfd_api::config] No config file provided. Using default
[2023-04-21T19:25:01Z INFO  bpfctl] Using TLS over TCP socket as transport
 UUID  Type  Name  Location  Metadata
```

Update the bpfd.service file to restrict access.
AFTER:
```
$ id
uid=1000(bmcfall) gid=1000(bmcfall) groups=1000(bmcfall),10(wheel),981(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

$ RUST_LOG=info bpfctl list
[2023-04-21T19:29:52Z WARN  bpfd_api::config] No config file provided. Using default
Error: CA Cert File does not exist

Caused by:
    Permission denied (os error 13)
```

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>