reenable image verification
sigstore/root-signing had a new sigining event that fixed the previous
issue. Update to new version of sigstore (0.11.0) and turn image
verification back on by default.

Also changed the error message returned to the user.

Original:

```
$ sudo bpfman load file --path bpfman/examples/go-xdp-counter/bpf_x86_bpfel.o --name "xdp_stats" xdp --iface eno3 --priority 35
Error: An error occurred. Unable to initialize ImageManager: Error spawning blocking task to build sigstore repo inside of tokio: Failed to parse root metadata: Invalid key ID 7247f0dbad85b147e1863bade761243cc785dcb7aa410e7105dd3d2b61a36d2c: calculated 0c87432c3bf09fd99189fdc32fa5eaedf4e4a5fac7bab73fa04a2e0fc64af6f5 at line 76 column 4
```

New:

```
$ sudo bpfman load file --path bpfman/examples/go-xdp-counter/bpf_x86_bpfel.o --name "xdp_stats" xdp --iface eno3 --priority 35
Error: An error occurred. Unable to initialize ImageManager: Error constructing Sigstore trust root: Failed to parse root metadata: Invalid key ID 7247f0dbad85b147e1863bade761243cc785dcb7aa410e7105dd3d2b61a36d2c: calculated 0c87432c3bf09fd99189fdc32fa5eaedf4e4a5fac7bab73fa04a2e0fc64af6f5 at line 76 column 4
```

Resolves: #1399

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>