docs: building docs after a PR merges fails
When a PR merges, a job from docs-build.yml is run. This is currently
failing with:

```
  pip install -r requirements.txt
  shell: /usr/bin/bash -e {0}
  :
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  2to3 python-is-python3

E: Package 'python' has no installation candidate
E: Unable to locate package install
Error: Process completed with exit code 100.
```

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>