Fix permissions error when loading bytecode from URL
When running as a systemd service, loading from a URL fails because
`/var/bpfd/bytecode/` is owned by `root:bpfd`, and the service is running user
`bpfd`:

```
$ bpfctl load --iface vethb2795c7 --priority 50 --from-image quay.io/bpfd/bytecode:gocounter
Error: status: Aborted, message: "failed to unpack `/var/bpfd/bytecode/bpf_bpfel.o`", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 03 Oct 2022 13:03:07 GMT", "content-length": "0"} }
```

Update user.sh to make sure /var/bpfd/bytecode/` is owned by `bpfd:bpfd`.

With the above change, when `./scripts.sh install` or `./scripts.sh init` is run,
`/var/bpfd/bytecode/` is owned by `bpfd:bpfd` as expected. If bpfd is then start
from binary instead of systemd service, it is being run as `root:bpfd`, and spawned
threads which are stripped of capabilites can't load from URL:

```
$ sudo ./target/debug/bpfctl load --iface vethb2795c7 --priority 50 --from-image quay.io/bpfd/bytecode:gocounter
Error: status: Aborted, message: "failed to unpack `/var/bpfd/bytecode/bpf_bpfel.o`", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 03 Oct 2022 14:19:50 GMT", "content-length": "0"} }
```

Update bpfd main.rs to only drop all capabilities on spawned threads if current
user is bpfd.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>