bpfd: bpfd panic on unload of id not owned by bpfd
bpfd panics on unload with an id that is not of a bpfd program:

```
 bpfctl unload 22222
Error = status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

Caused by:
    0: transport error
    1: connection error: unexpected end of file
    2: unexpected end of file
```

```
Oct 02 16:53:54 ebpf03 bpfd[1032526]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', bpfd/src/bpf.rs:618:50
Oct 02 16:53:54 ebpf03 bpfd[1032526]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>