bpfd panic when ebpf program fails to load
bpfd panics with 'map_pin_path must be set after load' when program fails to load

```
$ bpfctl load-from-file --path /run/bpfd/examples/xdp_pass_kern.o --name "pass" xdp --iface vethff657c7 --priority 35
Error = status: Aborted, message: "channel closed", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 29 Sep 2023 02:40:23 GMT", "content-length": "0"} }
Error: Failed to execute request
```

Logs:
```
Sep 28 22:40:22 ebpf03 bpfd[694889]: Map vethff657c7 to 14
Sep 28 22:40:23 ebpf03 bpfd[694889]: thread 'main' panicked at 'map_pin_path must be set after load', bpfd/src/bpf.rs:305:14
Sep 28 22:40:23 ebpf03 bpfd[694889]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 28 22:40:23 ebpf03 bpfd[694889]: RPC load error: RecvError(
                                         (),
                                     )
Sep 28 22:40:23 ebpf03 systemd[1]: bpfd.service: Main process exited, code=exited, status=101/n/a
Sep 28 22:40:23 ebpf03 systemd[1]: bpfd.service: Failed with result 'exit-code'.
```

Logic to manage the map_pin_path needs to be updated for error leg path.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>