build: bump netlink-packet-route to 0.19
Getting build error:

```
$ cargo +nightly clippy --all -- --deny warnings
    Checking bpfman v0.4.0-dev (/home/bmcfall/src/bpfman/bpfman)
error[E0308]: mismatched types
    --> bpfman/src/multiprog/tc.rs:187:31
     |
187  |                     .contains(&NelinkTcAttribute::Kind(qdisc_name.clone()))
     |                      -------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `TcAttribute`, found `netlink_packet_route::tc::TcAttribute`
     |                      |
     |                      arguments to this method are incorrect
     |
     = note: `netlink_packet_route::tc::TcAttribute` and `TcAttribute` have similar names, but are actually distinct types
note: `netlink_packet_route::tc::TcAttribute` is defined in crate `netlink_packet_route`
    --> /home/bmcfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/netlink-packet-route-0.18.1/src/tc/attribute.rs:32:1
     |
32   | pub enum TcAttribute {
     | ^^^^^^^^^^^^^^^^^^^^
note: `TcAttribute` is defined in crate `netlink_packet_route`
    --> /home/bmcfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/netlink-packet-route-0.19.0/src/tc/attribute.rs:32:1
     |
32   | pub enum TcAttribute {
     | ^^^^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `netlink_packet_route` are being used?
note: method defined here
    --> /home/bmcfall/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:2509:12
     |
2509 |     pub fn contains(&self, x: &T) -> bool
     |            ^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `bpfman` (bin "bpfman") due to 1 previous error
```

bpfman is locked at netlink-packet-route 0.18 but rtnetlink requires
0.19. So bump bpfman to 0.19.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>