bpfctl calls fail when using Unix socket
When using a Unix socket, bpfctl calls to bpfd fail:

```
$ bpfctl list
Error = transport error

Caused by:
    0: error trying to connect: Connecting to HTTPS without TLS enabled
    1: Connecting to HTTPS without TLS enabled
Error: Failed to execute request
```

To use a Unix socket, add/modify the bpfd.toml file and restart bpfd:

```
sudo vi /etc/bpfd/bpfd.toml
[[grpc.endpoints]]
  type = "unix"
  enabled = true
  path = "/run/bpfd/bpfd.sock"
```

The fix is to update the address being passed to bpfd.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>