rpm: RPM builds failing
Upstream RPM builds are failing:

```
  --- stderr
  Missing dependency: cmake
  thread 'main' panicked at /builddir/build/BUILD/bpfman-3b1aa1d0c42bd6f2dfef1d7cf27f4b7362307e49/vendor/aws-lc-sys/builder/main.rs:382:40:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

aws-lc-sys was added as a dependency in #1406 which requires cmake.
Adding cmake to the RPM builds.

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>