bpfd shouldn't exit based on invalid input
bpfd was exiting when invalid image was entered:
```
$ ./go-xdp-counter -iface vethff657c7 -image /quay.io/bpfd-bytecode/go-xdp-counter:latest
2023/05/04 14:10:30 Using Input: Interface=vethff657c7 Priority=50 Source=/quay.io/bpfd-bytecode/go-xdp-counter:latest
2023/05/04 14:10:30 Reading /etc/bpfd/gocounter.toml ...
2023/05/04 14:10:30 Read /etc/bpfd/gocounter.toml failed: err open /etc/bpfd/gocounter.toml: no such file or directory
2023/05/04 14:10:30 rpc error: code = Aborted desc = channel closed
```
Logs:
```
May 04 14:10:30 ebpf03 bpfd[171652]: Map vethff657c7 to 14
May 04 14:10:30 ebpf03 bpfd[171652]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to Parse bytecode Image URL: invalid reference format
May 04 14:10:30 ebpf03 bpfd[171652]: Caused by:
May 04 14:10:30 ebpf03 bpfd[171652]:     invalid reference format', bpfd/src/bpf.rs:576:85
May 04 14:10:30 ebpf03 bpfd[171652]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 04 14:10:30 ebpf03 bpfd[171652]: RPC load error: RecvError(
                                         (),
                                     )
May 04 14:10:30 ebpf03 systemd[1]: bpfd.service: Main process exited, code=exited, status=101/n/a
May 04 14:10:30 ebpf03 systemd[1]: bpfd.service: Failed with result 'exit-code'.
```

Update `bpfd/src/bpf.rs` to remove `.await?;` and process error in load_xdp_command(), load_tc_command()
and load_tracepoint_command().

Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>